version: '3.1'

services:
  backend:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.backend
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    image: jmucc_backend:latest
    ports:
      - "4000:4000"
  frontend:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      args:
        - PORT=${PORT}
    image: jmucc_frontend:latest
    ports:
      - "${PORT}:${PORT}"