version: '3.1'

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "27017:27017"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: jmucc_backend:latest
    ports:
      - "4000:4000"
    # depends_on:
    #   - "mongo"
    env_file:
      - ./.env
  frontend:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    image: jmucc_frontend:latest
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"