FROM node:16-alpine 
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
RUN yarn build
ENV NODE_ENV production
ARG FRONTEND_PORT=3000
EXPOSE $FRONTEND_PORT
# Start the app
CMD [ "npx", "serve", "build" ]