version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: jmucc_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
    env_file:
      - ./.env
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: jmucc_frontend:latest
    ports:
      - "3000:3000"